### ISSUE TITLE
Migrate to GitHub WIKI 

### ISSUE THREAD

**Issue by kshitijrajsharma** [osgeonepal/RollingConvo#2]
- For rolling docs, we have Google Docs so far, Plan is to migrate existing [rolling doc ](https://docs.google.com/document/d/19Ge4eur21vhWZ_JGhyn3RO4XsfoCr6jRvKEzcKUVMIc/edit) to [Github Wiki ](https://github.com/osgeonepal/RollingConvo/wiki) so that it will be more collaborative and easy to maintain also we need to reference this in to official[ osgeo wiki](https://wiki.osgeo.org/wiki/Nepal)

**Comment by kshitijrajsharma** [comment]
You can use : https://www.makeareadme.com/ for formatting .md files

**Comment by aashish66** [comment]
I am interested ,can I?

**Comment by kshitijrajsharma** [comment]
Sure , Go ahead !
