### ISSUE TITLE
Add doc about how to start contributing

### ISSUE THREAD

**Issue by kshitijrajsharma** [osgeonepal/RollingConvo#5]
Plan is to have clear doc specially for beginners in osgeonepal community about how to start and we can start engaging people directly here !

**Comment by subashtiwari1010** [comment]
I am interested.

**Comment by kshitijrajsharma** [comment]
@subashtiwari1010  Sure Go Ahead !

**Comment by aashish66** [comment]
I am interested ,can I start?

**Comment by kshitijrajsharma** [comment]
@aashish66  Sovas is working on this, feel free to pick another !
